name: my_app
description: "A new Flutter project."
publish_to: 'none'  # This prevents accidental publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  provider: ^6.0.0
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2

  # Uncomment the line below and add a proper version if you plan to use http_certificate_pinning
  # http_certificate_pinning: ^version_here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
